title: "Tanades' Write-Ups" 
description: "Welcome to my blog! Here I will be uploading my write-ups to develop my reporting skills."
author:
  name: "Álvaro Corrionero"
  email: "tanades.github.com.jaywalker973@passfwd.com"
  url: "https://github.com/Tanades/Tanades.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Tanades"
year : "2024"
google_analytics: "G-R7S7X062ZG"
